config/routes.rb
Rails.application.routes.draw do

  get '/home',to:'users#home'
  get '/like',to:'users#like'
  get '/break',to:'users#break'
  root 'sessions#new'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :homes, only: [:index]
  resources :relationships, only: [:create, :destroy]
  resources :breakships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/breakship.rb
class Breakship < ApplicationRecord
  belongs_to :breaked, class_name: "User"
  belongs_to :breaker, class_name: "User"
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true,uniqueness: true
  validates :sexe, presence: true
  validates :profil, presence: true
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password

  mount_uploader :profil, ProfileUploader
  before_validation { name.downcase! }

  #followship
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy

  has_many :followers, through: :passive_relationships, source: :follower
  has_many :following, through: :active_relationships, source: :followed


  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end


  #breakship
  has_many :active_breakships, foreign_key: 'breaker_id', class_name: 'Breakship', dependent: :destroy
  has_many :passive_breakships, foreign_key: 'breaked_id', class_name: 'Breakship', dependent: :destroy

  has_many :breakers, through: :passive_breakships, source: :breaker
  has_many :breaking, through: :active_breakships, source: :breaked

  def break!(other_user)
    active_breakships.create!(breaked_id: other_user.id)
  end

  def breaking?(other_user)
    active_breakships.find_by(breaked_id: other_user.id)
  end

  def unbreak!(other_user)
    active_breakships.find_by(breaked_id: other_user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/breakships_controller.rb
class BreakshipsController < ApplicationController
  def create
    if logged_in?
      @user = User.find(params[:breakship][:breaked_id])
      current_user.break!(@user)
      redirect_to home_path
    end
  end

  def destroy
    @user = Breakship.find(params[:id]).breaked
    current_user.unbreak!(@user)
    redirect_to home_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

def index
    @users = User.all.where.not(sexe: current_user.sexe)
    render json: @users
end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    if logged_in?
      @user = User.find(params[:relationship][:followed_id])
      current_user.follow!(@user)
      redirect_to home_path
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to like_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end
  def create
    user = User.find_by(name: params[:session][:name].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to home_path
   else
     flash.now[:danger] = 'connexion échouée'
    render :new
   end
  end

    def destroy
     session.delete(:user_id)
     flash[:notice] = 'vous êtes déconnecté'
     redirect_to new_session_path
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :login_required, only: [:new, :create]


  def break
    @user = User.find(current_user.id)
  end

  def like
    @user = User.find(current_user.id)
  end

  def home
    @users = User.all.where.not(sexe: current_user.sexe)
    @userData = @users.length()
    @currentData = rand(0...@userData)
    @user = @users[@currentData]
    @i = 0
    while current_user.following?(@user) &&  @i<10 do
      @currentData = rand(0...@userData)
      @user = @users[@currentData]
      @i=@i+1
    end
  end

  def index
    @user = User.find(8)
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
        render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'profile mise a jour !'
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = 'profil supprimee!'
    redirect_to recettes_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :sexe, :profil, :bio, :age, :pays, :ville, :password, :password_confirmation)
  end
  def set_user
   @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breakships_helper.rb
module BreakshipsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
   current_user.present?
 end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/breakships/create.html.erb
<h1>Breakships#create</h1>
<p>Find me in app/views/breakships/create.html.erb</p>

app/views/breakships/destroy.html.erb
<h1>Breakships#destroy</h1>
<p>Find me in app/views/breakships/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fresh</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

  </head>
  <body>
    <% flash.each do |key, value|%>
      <%= content_tag(:div,value,class:"alert alert-#{key}")%>
    <% end%>
    <div class="container">
      <header>
        <% if logged_in? %>
        <p><%= link_to "Home", home_path, class:"fas fa-home"%></p>
          <p><%= link_to " Mon profil", user_path(current_user.id), class:"fas fa-user-alt", id:"showProfile"%></p>
          <p><%= link_to " Mes lapins", like_path(current_user.id), class:"fas fa-heart", id:"coupDeCoeur"%></p>
          <p><%= link_to " Mes Canards", break_path(current_user.id), class:"fas fa-heart-broken", id:"break"%></p>
          <p><%= link_to " Deconnecter", session_path(current_user.id), method: :delete, class:"fas fa-sign-out-alt" %>
        <% else %>
          <p><a href="/users/new"><i class="fas fa-sign-out-alt"> S'incrire</i></a></p>
          <p><a href="/sessions/new"><i class="fas fa-sign-out-alt"> Se connecter</i></a></p>
        <% end %>
      </header >
        <%= yield %>
    </div>
  </body>
</html>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
        <% if @user.errors.any? %>
            <div id="error_explanation">
                <h2>
                    <%= pluralize(@user.errors.count, "error" ) %> prohibited this <%= @user.name %> from being saved:
                </h2>
                <ul>
                    <% @user.errors.full_messages.each do |message| %>
                        <li>
                            <%= message %>
                        </li>
                        <% end %>
                </ul>
            </div>
        <% end %>
          <%= f.label :profil %>
          <br>
          <%= f.file_field :profil, autofocus: true%>
          <br>
          <%= f.label :name %>
          <br>
          <%= f.text_field :name,autofocus: true, autocomplete: "name", required: true %>
          <br>
          <%= f.label :sexe %>
          <br>
          <%= f.text_field :sexe, autofocus: true, autocomplete: "sexe", required: true %>
          <br>
          <%= f.label :password %>
          <br>
          <%= f.password_field :password, autofocus: true, required: true %>
          <br>
          <%= f.label :password_confirmation %>
          <br>
          <%= f.password_field :password_confirmation, autofocus: true, required: true %>
          <br>
          <br>
          <%= f.submit "CREER UN COMPTE" %>
<% end %>

app/views/users/break.html.erb
<div class="likes" id="userLikes">
    <h3>Mes Canards</h3>
    <ul class="fav-user" id="fav-user">
      <% @user.breaking.each do |breaking|%>
      <li>
        <%= image_tag breaking.profil.url%>
        <span><a href="/users/<%= breaking.id %>"><%= breaking.name %></a></span>
        <%= form_with(model: current_user.active_breakships.find_by(breaked_id: breaking.id), method: :delete ) do |f| %>
          <%= f.submit "X",class:"clear fas fa-window-close" %>
        <% end %>
      </li>
    <% end %>
    </ul>
</div>

app/views/users/edit.html.erb
<div class="  form ">
  <%= form_with(model: @user, local: true) do |f| %>
          <% if @user.errors.any? %>
              <div id="error_explanation">
                  <h2>
                      <%= pluralize(@user.errors.count, "error" ) %> prohibited this <%= @user.name %> from being saved:
                  </h2>
                  <ul>
                      <% @user.errors.full_messages.each do |message| %>
                          <li>
                              <%= message %>
                          </li>
                          <% end %>
                  </ul>
              </div>
          <% end %>
            <%= f.label :profil %>
            <br>
            <%= f.file_field :profil, autofocus: true%>
            <br>
            <%= f.label :name %>
            <br>
            <%= f.text_field :name,autofocus: true, autocomplete: "name", required: true %>
            <br>
            <%= f.label :sexe %>
            <br>
            <%= f.text_field :sexe, autofocus: true, autocomplete: "sexe", required: true%>
            <br>
            <%= f.label :age %>
            <br>
            <%= f.text_field :age, autofocus: true, autocomplete: "age", required: true%>
            <br>
            <%= f.label :pays %>
            <br>
            <%= f.text_field :pays, autofocus: true, autocomplete: "pays", required: true%>
            <br>
            <%= f.label :ville %>
            <br>
            <%= f.text_field :ville, autofocus: true, autocomplete: "ville", required: true%>
            <br>
            <%= f.label :bio %>
            <br>
            <%= f.text_field :bio, autofocus: true, autocomplete: "bio", required: true%>
            <br>
            <%= f.label :password %>
            <br>
            <%= f.password_field :password, autofocus: true, required: true %>
            <br>
            <%= f.label :password_confirmation %>
            <br>
            <%= f.password_field :password_confirmation, autofocus: true, required: true %>
            <br>
            <br>
            <%= f.submit "MODIFIER UN COMPTE" %>
  <% end %>

</div>

app/views/users/home.html.erb
<div class="bodyBag">
  <% if @i == 10 %>
  <div class="">
    <div id="container" class="userContainer">
       <div id="userShow" class="userShow">
           <div class=" userDetail">
           </div>
        </div>
    </div>
    <div class="popup-container" id="user-popup">
       <div class="popup">
         <a href="/like" id="close-popup" class="close-popup"><i class="fas fa-times"></i></a>
         <div class="user-info" id="user-info">
           <p>Vous avez tout vu</p>
         </div>
         </div>
      </div>
  </div>
  <% else %>
<div class="bodyBag" id="bodyBag">
    <div id="container" class="userContainer">

      <% unless current_user.breaking?(@user) %>
      <div class="fav-btn">
        <%= form_with(model: current_user.active_breakships.build(breaked_id: @user.id))  do |f| %>
          <%= f.hidden_field :breaked_id %>
          <%= f.submit "Canard" %>
          <i class=" fas fa-heart-broken active"></i>
        <% end %>
      </div>
    <% end %>
       <div id="userShow" class="userShow">
           <%= image_tag @user.profil.url, id:"userProfile"%>
           <div class=" userDetail">
           <div>
             <h3 id="userName"><%= @user.name %></h3>
             <p id="userSexe"><%= @user.sexe %></p>
           </div>
           <div class="user-body ">
             <button class="fav-btn">
               <i class="fas fa-heart active"> 50 %</i>
             </button>
           </div>
         </div>
       </div>
       <% unless current_user.following?(@user) %>
       <div class="fav-btn">
         <%= form_with(model: current_user.active_relationships.build(followed_id: @user.id))  do |f| %>
            <%= f.hidden_field :followed_id %><i class="fas fa-heart active"></i>
            <%= f.submit "Lapin!" , class:"fas fa-heart active" %>
          <% end %>
       </div>
       <% end %>
       </div>
     </div>
     <div class="popup-container hidden" id="user-popup">
        <div class="popup">
          <button id="close-popup" class="close-popup"><i class="fas fa-times"></i></button>
            <%= image_tag @user.profil.url, id:"userProfile"%>
            <div class="right">
            <h1><%= @user.name %></h1>
            <div class="fav-btn">
              <i class="fas fa-heart active"> 50% </i> <small>de compatibilité avec <%= @user.name %></small>
            </div>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo aliquam, consequuntur iste, quo quasi
              facere libero, assumenda cum similique voluptates quis id deleniti soluta? Minus culpa magnam ullam dolore
              doloribus?</p>
            <div>
            </div>
          </div>
          </div>
      </div>
      </div>
<% end %>
<%= javascript_pack_tag 'home' %>

app/views/users/index.html.erb
<div id="container" class="scrollcontainer">
    <button class=" scroll scroll-left" id="scroll-left">
      <i class=" fas fa-heart-broken active"></i>
    </button>
    <div id="userShow" class="userShow">

    </div>
    <div>
      <button  class=" scroll scroll-right" id="scroll-right">
        <i class="fas fa-heart active"></i>
      </button>
    </div>
</div>
<div class="popup-container hidden" id="user-popup">
  <div class="popup">
    <button id="close-popup" class="close-popup"><i class="fas fa-times"> fermer</i></button>
    <div class="user-info" id="user-info">
    </div>
  </div>
</div>

<%= javascript_pack_tag 'home' %>

app/views/users/like.html.erb
<div class="likes" id="userLikes">
    <h3>Mes Lapins</h3>
    <ul class="fav-user" id="fav-user">
      <% @user.following.each do |following|%>
      <li>
        <%= image_tag following.profil.url%>
        <span><a href="/users/<%= following.id %>"><%= following.name %></a></span>
        <%= form_with(model: current_user.active_relationships.find_by(followed_id: following.id), method: :delete ) do |f| %>
          <%= f.submit "X",class:"clear fas fa-window-close" %>
        <% end %>
      </li>
    <% end %>
    </ul>
</div>

app/views/users/new.html.erb
<div class="  form ">
  <%=render 'form' %>
</div>

app/views/users/show.html.erb
<div id="profil">
    <a href="/home" id="close-popup" class="close-popup"><i class="fas fa-times"> fermer</i></a>
    <div id="userShow" class="userShow">
        <%= image_tag @user.profil.url, id:"userProfile"%>
        <div class=" userDetail">
          <div>
            <h3 id="userName"><%= @user.name %></h3>
            <p id="userSexe"><%= @user.sexe %></p>
          </div>
          <div class="user-body ">
            <button class="fav-btn">
              <i class="fas fa-heart active"> 50 %</i>
            </button>
          </div>
        </div>
    </div>
  <div class="userBio">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>
</div>